

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
      - celery
    environment:
      - DJANGO_SETTINGS_MODULE=core.production
      - DATABASE_URL=postgres://postgres:1234@db:5432/dhtdb

  db:
    image: postgres:15.2
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=dhtdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  redis:
    image: redis:6.2
    ports:
      - 6379:6379

  celery:
    build: .
    command: celery -A core.celery worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - DATABASE_URL=postgres://postgres:1234@db:5432/dhtdb

volumes:
  postgres_data:
