# Generated by Django 5.0.7 on 2024-08-26 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0002_dailymood_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailymood',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
