# Generated by Django 5.0.7 on 2024-08-28 21:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mental', '0004_dailyuserquote_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='mood',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
