# Generated by Django 5.0.7 on 2024-08-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitinstance',
            name='habit_type',
        ),
        migrations.AlterField(
            model_name='habitinstance',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
