# Generated by Django 5.0.7 on 2024-08-09 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0003_alter_recurringhabit_user_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='singlehabit',
            name='reminder_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 15, 59, 21, 799976, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
