# Generated by Django 5.0.7 on 2024-08-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0005_habitinstance_celery_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitinstance',
            name='status',
            field=models.CharField(choices=[('DONE', 'Done'), ('PENDING', 'Pending'), ('UNDONE', 'Undone'), ('NOTIFIED', 'Notified')], default='PENDING', max_length=200),
        ),
    ]
