# Generated by Django 5.0.7 on 2024-08-30 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0011_userhabitsuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecurringHabit',
            new_name='Habit',
        ),
        migrations.RemoveField(
            model_name='habitinstance',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='habitinstance',
            name='object_id',
        ),
        migrations.AddField(
            model_name='habitinstance',
            name='habit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='habit.habit'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SingleHabit',
        ),
    ]
