# Generated by Django 5.0.7 on 2024-08-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0013_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
