# Generated by Django 5.0.7 on 2024-09-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0015_pushnotificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='notif_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='notif_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
