# Generated by Django 5.0.7 on 2024-09-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habit', '0016_habit_notif_body_reminder_notif_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhabitsuggestion',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userhabitsuggestion',
            name='notif_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userhabitsuggestion',
            name='recurrence_seconds',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
