# Generated by Django 5.0.7 on 2024-08-12 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='score',
        ),
    ]
