# Generated by Django 5.0.7 on 2024-08-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_profile_allowed_habits_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_change_profile',
            field=models.BooleanField(default=False),
        ),
    ]
