# Generated by Django 5.0.7 on 2024-08-31 22:04

from django.db import migrations


def create_missing_profiles(apps, schema_editor):
    CustomUser = apps.get_model('user', 'CustomUser')
    Profile = apps.get_model('user', 'Profile')
    UserScore = apps.get_model('scoring', 'UserScore')
    ToDoList = apps.get_model('habit', 'ToDoList')

    for user in CustomUser.objects.all():
        if not Profile.objects.filter(user=user).exists():
            Profile.objects.create(user=user)

        if not UserScore.objects.filter(user=user).exists():
            UserScore.objects.create(user=user)

        if not ToDoList.objects.filter(user=user).exists():
            ToDoList.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_profile_allowed_change_profile'),
    ]

    operations = [
        migrations.RunPython(create_missing_profiles),
    ]
